-- ============================================================
-- Migration 019: Morning Briefing tone + tagline cache columns
-- Feature: Phase 7 D6 tonal rotation (Energetic / Observant / Celebratory)
-- Purpose: Persist Claude-generated `tagline` and the rotated `tone` on
--          daily_check_in so the home Kumustahan hero serves both from
--          cache after the first generation per user per day. Pre-migration,
--          /api/morning-briefing recomputes tagline + tone on every cache hit
--          (re-runs Claude per day, see route.ts lines 25-31 + 340-352).
--
-- Owning table: public.daily_check_in (extends existing cache columns
--               briefing_content, briefing_generated_at added in migration 012).
-- New table not needed — same (user_id, check_in_date) cache key.
--
-- RLS: inherited from existing daily_check_in policies (auth.uid() = user_id
--      SELECT/INSERT/UPDATE, see migration 006). No new policies required —
--      column-level access is governed by row-level policies already in place.
--
-- Soft-delete: inherited from existing deleted_at TIMESTAMPTZ NULL on
--              daily_check_in (migration 006).
--
-- Data classification: AI-generated content. No new PII. Tagline is short
--                      conversational Filipino copy; tone is a 3-value enum.
--
-- Rollback:
--   ALTER TABLE public.daily_check_in DROP COLUMN IF EXISTS briefing_tone;
--   ALTER TABLE public.daily_check_in DROP COLUMN IF EXISTS briefing_tagline;
-- ============================================================

-- --- Add tagline column (≤80 chars enforced at app layer; TEXT for safety) ---
ALTER TABLE public.daily_check_in
  ADD COLUMN IF NOT EXISTS briefing_tagline TEXT NULL;

-- --- Add tone column with CHECK constraint matching MorningTone TS union ---
ALTER TABLE public.daily_check_in
  ADD COLUMN IF NOT EXISTS briefing_tone TEXT NULL
    CHECK (briefing_tone IS NULL OR briefing_tone IN ('energetic', 'observant', 'celebratory'));

COMMENT ON COLUMN public.daily_check_in.briefing_tagline
  IS 'Cached one-liner tagline (≤80 chars) for the Kumustahan hero, generated by Claude alongside briefing_content. NULL when fallback templates are served (no_credits path).';

COMMENT ON COLUMN public.daily_check_in.briefing_tone
  IS 'Tone register for the tagline: energetic | observant | celebratory. Picked deterministically per day-of-year, persisted alongside the tagline so cache hits return matching pair.';
